import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./Components/Navbar";
import AuthProvider from "./services/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  
    title: {
      template: '%s | Next New',
      default: 'Next | Next New',
    },
  
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <AuthProvider>
     <body className={inter.className}>
       <Navbar/>
        {children}
        <footer className="text-center">
          this is footer
        </footer>
        </body>
     </AuthProvider>
    </html>
  );
}
